### ISSUE TITLE
Not possible to activate IdP

### ISSUE THREAD

**Issue by DoGab** [zitadel/terraform-provider-zitadel#30]
It currently is possible to configure IdPs on organization level. However the IdP stays inactive and can only be activated manually through the UI. 

Add the possibility to activate/deactivate IdPs from Terraform aswell.

**Comment by stebenz** [comment]
Could it be that they are just displayed as "not available", or could you give me an example?
IDPs that I created through the terraform provider are displayed as active, but not available, as you have to add them to your login policy for that.

**Comment by DoGab** [comment]
Yes exactly, they are displayed as active but are not available. I didn't know that it's possible to add the IdP to the login policy. So this is possible then. I expected it to be a flag on the IdP resource itself to make it available :)

**Comment by stebenz** [comment]
> Yes exactly, they are displayed as active but are not available. I didn't know that it's possible to add the IdP to the login policy. So this is possible then. I expected it to be a flag on the IdP resource itself to make it available :)

Seems like there is a bug around with the display of the correct available IDPs, we are currently working on a fix, but first have to determine if it's only backend or frontend as well.
Should not impact the terraform provider at all, so I will close this issue as soon as we have a fix.

**Comment by stebenz** [comment]
created issue on zitadel/zitadel repository https://github.com/zitadel/zitadel/issues/4670

**Comment by stebenz** [comment]
close as issue in zitadel/zitadel repository is closed

**Comment by yann-soubeyrand** [comment]
Hi,

I see that this issue is resolved, but I just created an LDAP identity provider at instance level on a recent ZITADEL (v2.65.1) and ZITADEL tells me that I have to activate the identity provider:
![Image](https://github.com/user-attachments/assets/475edc88-a580-44e5-8ec9-fe474a1148a2)
![Image](https://github.com/user-attachments/assets/ecd38eae-85b3-471a-9e04-b777209637ba)

I can’t find a way to do it with Terraform. Did I miss something?
